### ISSUE TITLE
about the dataset

### ISSUE THREAD

**Issue by yuzhuogu** [csccsccsccsc/cpp-net#2]
The link to the second data set is now inaccessible. And there are so many data in the third link and which to download?

**Comment by csccsccsccsc** [comment]
BBBC006:
Since we only use the in-focus images, you can download the data here:
https://data.broadinstitute.org/bbbc/BBBC006/BBBC006_v1_images_z_16.zip
Also, we only evaluate the models on the Hoechst images, i.e., the '*_w1*.tif' images.
