### ISSUE TITLE
training process of SAP model

### ISSUE THREAD

**Issue by geek-APTX4869** [csccsccsccsc/cpp-net#3]
dear author:
  training process of SAP model 用的什么数据集呢

**Comment by csccsccsccsc** [comment]
比如，在DSB2018和BBBC006中，采用一般实验一致的训练集/验证集划分方式，直接使用对应的掩模数据生成 多边形 / 边界检测 / boundibng box坐标等对应标签即可。
在PanNuke中，则根据当前交叉验证轮次选取训练验证的划分方式，其他均一样。
