### ISSUE TITLE
Training for PanNuke

### ISSUE THREAD

**Issue by FabianHoerst** [csccsccsccsc/cpp-net#4]
Dear Authors,

is there any Code for training the network on the PanNuke data available or even pretrained models published to check the results of the PanNuke dataset? I am interested in the Detection-Results of the PanNuke data but I am not able to find the training code for that.

Thanks in advance!

**Comment by csccsccsccsc** [comment]
Sorry for my late answer. I have updated the codes of experiments on PanNuke.

**Comment by FabianHoerst** [comment]
Hello, could you then also provide all necessary parameters you used for training? E.g., max_distance of the stardist algorithm is nowhere mentioned: `getPanNukeDataLoaders() missing 1 required positional argument: 'max_dist'`
